name: Maven Build

on:
  push

jobs:
  build:
    name: Maven Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
          cache: 'maven'

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: mvn test
        if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
        run: |
          mvn -B -T1C clean test
        shell: bash

      - name: mvn test (Windows)
        if: runner.os == 'Windows'
        run: |
          mvn -B -T1C clean test
        shell: cmd
